- type: entity
  id: SlimeGrinderMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: slime grinder machine board
  description: A machine printed circuit board for a slime grinder.
  components: # Maybe change this recipe later.
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: SlimeGrinder
    stackRequirements:
      Manipulator: 5
      Steel: 5
    tagRequirements:
      Knife:
        amount: 2
        defaultPrototype: KitchenKnife
        examineName: construction-insert-info-examine-name-knife
